"""
Centralized, Curated Destination Catalog for TourCraze 'Get Inspired' Collections.
Contains 30+ unique, non-repeating, highly descriptive cue cards for every category.
"""

DESTINATIONS_DATA = [
    # =========================================================================
    # 🏔️ MOUNTAINS (30 Unique Destinations & Hidden Spots)
    # =========================================================================
    {
        "name": "Manali & Solang Valley",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Jun",
        "budget": "₹15,000 / 5 Days",
        "description": "Snow-dusted Himalayan peaks, roaring Beas river, Rohtang Pass adventures, and cozy deodar log cabins.",
        "categories": ["mountains"],
        "tag": "🏔️ Snow & Alpine",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "Spiti Valley & Kaza",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "May - Oct",
        "budget": "₹24,000 / 6 Days",
        "description": "Cold desert moonscapes, 1000-year-old Key Monastery, Chandratal lake, and world's highest post office at Hikkim.",
        "categories": ["mountains"],
        "tag": "💎 Hidden Gem",
        "days": 6,
        "style": "Adventure"
    },
    {
        "name": "Gulmarg & Pahalgam",
        "state": "Kashmir",
        "img": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Year-Round",
        "budget": "₹32,000 / 6 Days",
        "description": "Asia's premier ski resort, world's highest gondola ride above clouds, saffron valleys, and alpine pine meadows.",
        "categories": ["mountains"],
        "tag": "❄️ Winter Paradise",
        "days": 6,
        "style": "Luxury"
    },
    {
        "name": "Chopta & Tungnath",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Apr - Nov",
        "budget": "₹12,000 / 3 Days",
        "description": "The mini-Switzerland of India with emerald bugyals, Deoria Tal mirror reflections, and highest Shiva shrine in the world.",
        "categories": ["mountains"],
        "tag": "🥾 Trekker's Secret",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Leh Ladakh & Pangong",
        "state": "Ladakh",
        "img": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Jun - Sep",
        "budget": "₹38,000 / 7 Days",
        "description": "Dramatic high-altitude mountain passes, shimmering blue Pangong Tso waters, and Hunder double-humped camel dunes.",
        "categories": ["mountains"],
        "tag": "🏍️ High Altitude",
        "days": 7,
        "style": "Adventure"
    },
    {
        "name": "Munnar & Anamudi",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹18,000 / 4 Days",
        "description": "Rolling emerald tea plantations, mist-shrouded green hill tops, and cool spice-scented mountain air.",
        "categories": ["mountains"],
        "tag": "🍵 Tea Trails",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Darjeeling & Tiger Hill",
        "state": "West Bengal",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun",
        "budget": "₹16,000 / 4 Days",
        "description": "UNESCO heritage Himalayan toy train, panoramic Kanchenjunga sunrises, and colonial vintage tea estates.",
        "categories": ["mountains"],
        "tag": "🚂 Heritage Toy Train",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Auli & Joshimath",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Dec - Mar",
        "budget": "₹22,000 / 4 Days",
        "description": "Glistening white ski slopes overlooked by Nanda Devi, coniferous forest slopes, and artificial lake vistas.",
        "categories": ["mountains"],
        "tag": "⛷️ Ski Resort",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Jibhi & Tirthan Valley",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹14,000 / 4 Days",
        "description": "Dense pine forests, wooden deodar bridges, crystal trout streams, and serene Jalori Pass day treks.",
        "categories": ["mountains"],
        "tag": "💎 Hidden Valley",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Ziro Valley",
        "state": "Arunachal Pradesh",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Mar",
        "budget": "₹26,000 / 5 Days",
        "description": "UNESCO heritage pine hills, sustainable Apatani paddy farmlands, and famous indie outdoor music festival.",
        "categories": ["mountains"],
        "tag": "🎋 Tribal Valley",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "Lansdowne",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹11,000 / 3 Days",
        "description": "Quiet cantonment hill town surrounded by thick oak and blue pine forests, colonial churches, and Bhulla Tal lake.",
        "categories": ["mountains"],
        "tag": "🌲 Quiet Cantonment",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Coonoor & Nilgiri Hills",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - May",
        "budget": "₹15,000 / 3 Days",
        "description": "Peaceful alternative to Ooty with Sim's Park botanical gardens, tea factories, and Dolphin's Nose viewpoint.",
        "categories": ["mountains"],
        "tag": "🍵 Nilgiri Tea Hills",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kausani & Nanda Devi View",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Apr",
        "budget": "₹13,000 / 3 Days",
        "description": "300 km uninterrupted panoramic view of Trishul, Nanda Devi and Panchachuli peaks in Kumaon hills.",
        "categories": ["mountains"],
        "tag": "🏔️ Himalayan Panorama",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kalpa & Kinnaur Kailash",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Apr - Oct",
        "budget": "₹21,000 / 5 Days",
        "description": "Apple orchard village facing the sacred Kinnaur Kailash massif, suicide point cliffs, and ancient Buddhist gompas.",
        "categories": ["mountains"],
        "tag": "💎 Hidden Kinnaur",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "Lachung & Yumthang Valley",
        "state": "North Sikkim",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Mar - Jun, Oct - Dec",
        "budget": "₹28,000 / 5 Days",
        "description": "The Valley of Flowers of the East, natural sulphur hot springs, Zero Point snowfields, and rhododendron blooms.",
        "categories": ["mountains"],
        "tag": "🌸 Valley of Flowers",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "Sethan & Hampta Pass Foothills",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Dec - Mar (Igloos), Jun - Oct (Treks)",
        "budget": "₹16,000 / 3 Days",
        "description": "Buddhist igloo village perched above Manali offering night stargazing, snowboarding, and crossover pass treks.",
        "categories": ["mountains"],
        "tag": "❄️ Igloo Village",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Bir Billing & Kangra Valley",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Jun",
        "budget": "₹14,000 / 3 Days",
        "description": "World's second highest paragliding takeoff site, Tibetan monasteries, tea gardens, and sunset landing sites.",
        "categories": ["mountains"],
        "tag": "🪂 Paragliding Capital",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Dhanaulti & Kanatal",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹12,000 / 3 Days",
        "description": "Serene eco-parks in deodar forests, apple orchard farm stays, Surkanda Devi ropeway, and snow views.",
        "categories": ["mountains"],
        "tag": "🌲 Deodar Forests",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Chikmagalur & Mullayanagiri",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹15,000 / 3 Days",
        "description": "Highest peak in Karnataka, fragrant Arabica coffee estates, Baba Budangiri hills, and forest waterfalls.",
        "categories": ["mountains"],
        "tag": "☕ Coffee Peak",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Vagamon & Pine Hills",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹13,000 / 3 Days",
        "description": "Verdant rolling meadows, pine forest walking trails, Kurisumala ashram, and cool mist-kissed Western Ghats breeze.",
        "categories": ["mountains"],
        "tag": "🌿 Green Meadows",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Khajjiar (Mini Switzerland)",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Mar - Jun, Oct - Dec",
        "budget": "₹14,000 / 3 Days",
        "description": "Saucer-shaped green plateau ringed by dense deodar pine trees with a floating island in the central lake.",
        "categories": ["mountains"],
        "tag": "🌲 Mini Switzerland",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Pelling & Skywalk",
        "state": "West Sikkim",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - May",
        "budget": "₹18,000 / 4 Days",
        "description": "India's first glass skywalk overlooking Chenrezig statue, Pemayangtse Monastery, and close-up views of Mount Kanchenjunga.",
        "categories": ["mountains"],
        "tag": "🌉 Glass Skywalk",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Tawang & Sela Pass",
        "state": "Arunachal Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Mar - Oct",
        "budget": "₹32,000 / 6 Days",
        "description": "India's largest Buddhist monastery, 13,700 ft Sela Pass lake, Madhuri Lake, and dramatic snowbound landscapes.",
        "categories": ["mountains"],
        "tag": "🛕 High Monastery",
        "days": 6,
        "style": "Adventure"
    },
    {
        "name": "Ranikhet & Chaubatia",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹12,000 / 3 Days",
        "description": "Queen's Meadow hill station famous for sprawling government fruit orchards, high-altitude golf course, and pine air.",
        "categories": ["mountains"],
        "tag": "🍎 Fruit Orchards",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kasol & Tosh Village",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹12,000 / 4 Days",
        "description": "Parvati Valley backpacking haven, Kheerganga hot spring trail, wooden Tosh homes, and roaring glacial rivers.",
        "categories": ["mountains"],
        "tag": "🎒 Backpacker Haven",
        "days": 4,
        "style": "Budget"
    },
    {
        "name": "Landour & Lal Tibba",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹15,000 / 3 Days",
        "description": "British cantonment above Mussoorie, Ruskin Bond's hometown, Char Dukan, and the Winterline sunset phenomenon.",
        "categories": ["mountains"],
        "tag": "📚 Colonial Heritage",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Valparai & Anamalai Hills",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "40 thrilling hairpin bends through rainforests leading to untouched tea estates and endemic Lion-tailed macaques.",
        "categories": ["mountains"],
        "tag": "🐆 Wildlife & Tea",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Shangarh & Sainj Valley",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹13,000 / 3 Days",
        "description": "Pristine Pandava-cleared meadow inside the Great Himalayan National Park with zero commercial noise.",
        "categories": ["mountains"],
        "tag": "💎 Secret Meadow",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Daringbadi (Kashmir of Odisha)",
        "state": "Odisha",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Nov - Feb",
        "budget": "₹10,000 / 3 Days",
        "description": "Eastern Ghats hill retreat featuring coffee gardens, pine forests, winter frost, and tribal craft villages.",
        "categories": ["mountains"],
        "tag": "🌲 Eastern Ghats",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Araku Valley & Ananthagiri Hills",
        "state": "Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Sep - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "Organic tribal coffee plantations, Million-year-old Borra Caves, and scenic Vistadome glass train ride.",
        "categories": ["mountains"],
        "tag": "☕ Tribal Coffee Valley",
        "days": 3,
        "style": "Family"
    },

    # =========================================================================
    # 🏖️ BEACH (30 Unique Destinations & Hidden Coastal Havens)
    # =========================================================================
    {
        "name": "South Goa & Palolem",
        "state": "Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - Mar",
        "budget": "₹22,000 / 4 Days",
        "description": "Crescent golden sand beaches, colorful beach shacks, sunset dolphin cruises, and laid-back coastal cafes.",
        "categories": ["beach"],
        "tag": "🌴 Tropical Vibes",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Gokarna & Om Beach",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 4 Days",
        "description": "5-Beach cliffside trail (Kudle, Om, Half Moon, Paradise), sacred temples, red laterite cliffs, and pristine coves.",
        "categories": ["beach"],
        "tag": "💎 Hidden Gem",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Havelock Island (Radhanagar)",
        "state": "Andaman & Nicobar",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - May",
        "budget": "₹42,000 / 6 Days",
        "description": "Voted Asia's best white sand beach with turquoise crystal lagoons, live coral snorkeling, and deep sea scuba diving.",
        "categories": ["beach"],
        "tag": "🤿 Scuba & Coral",
        "days": 6,
        "style": "Luxury"
    },
    {
        "name": "Varkala Cliff Beach",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹18,000 / 4 Days",
        "description": "Dramatic red laterite cliffs directly overlooking the Arabian Sea, bohemian sunset cafes, and natural mineral springs.",
        "categories": ["beach"],
        "tag": "🌅 Cliffside Views",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Pondicherry Promenade",
        "state": "Puducherry",
        "img": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹15,000 / 3 Days",
        "description": "French colonial seafront villas, cobblestone White Town boulevards, surfing beaches, and chic seaside bakeries.",
        "categories": ["beach"],
        "tag": "🥖 French Riviera",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kovalam & Lighthouse Beach",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹19,000 / 4 Days",
        "description": "Iconic striped lighthouse overlooking calm crescent bays, traditional Ayurvedic wellness spas, and fresh seafood.",
        "categories": ["beach"],
        "tag": "🏮 Lighthouse Bay",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Diu Island & Nagoa Beach",
        "state": "Daman & Diu",
        "img": "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Apr",
        "budget": "₹14,000 / 3 Days",
        "description": "Portuguese fortress sea-walls, pristine horseshoe beaches, rare Hoka palm trees, and breezy quiet shores.",
        "categories": ["beach"],
        "tag": "🏰 Coastal Fort",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Marari Beach",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹20,000 / 3 Days",
        "description": "Quiet fishing hamlet with endless coconut palm groves, thatched luxury eco-resorts, and serene golden coastlines.",
        "categories": ["beach"],
        "tag": "🥥 Eco Coastal Retreat",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Tarkarli & Malvan",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Apr",
        "budget": "₹16,000 / 3 Days",
        "description": "Sindhudurg sea fort, transparent Karli river backwaters, scuba coral diving, and authentic Malvani seafood curries.",
        "categories": ["beach"],
        "tag": "🤿 Scuba & Forts",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Neil Island (Shaheed Dweep)",
        "state": "Andaman & Nicobar",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - May",
        "budget": "₹28,000 / 4 Days",
        "description": "Natural rock bridge, Laxmanpur sunset sands, Bharatpur coral reef waters, and laid-back bicycle rides.",
        "categories": ["beach"],
        "tag": "🪸 Natural Bridge",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Mandarmani Beach",
        "state": "West Bengal",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Oct - Mar",
        "budget": "₹11,000 / 3 Days",
        "description": "India's longest drivable beach beach with red ghost crabs, tranquil morning tides, and seaside fish fries.",
        "categories": ["beach"],
        "tag": "🦀 Red Crab Coast",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Puri Golden Beach",
        "state": "Odisha",
        "img": "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "Blue Flag certified clean golden beach, sacred Jagannath temple heritage, and world-renowned sand art festivals.",
        "categories": ["beach"],
        "tag": "🚩 Blue Flag Certified",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Alibaug & Kashid",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Apr",
        "budget": "₹14,000 / 2 Days",
        "description": "White sand waves, watersports, historic Kolaba sea fort accessible during low tide, and coastal homestays.",
        "categories": ["beach"],
        "tag": "🏰 Sea Fort",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Kappad Beach",
        "state": "Kozhikode, Kerala",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Sep - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "Historic beach where Vasco da Gama landed in 1498, Blue Flag certified promenade, and rock-studded shores.",
        "categories": ["beach"],
        "tag": "📜 Historic Coast",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Ganpatipule Beach",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "400-year-old self-manifested Ganesha temple right on white sandy shores surrounded by lush mango and betel nut trees.",
        "categories": ["beach"],
        "tag": "🛕 Coastal Temple",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Agonda & Cola Beach",
        "state": "South Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - Apr",
        "budget": "₹21,000 / 4 Days",
        "description": "Hidden emerald freshwater lagoon separated from the sea by a sandbar, turtle nesting sites, and silent sunset shores.",
        "categories": ["beach"],
        "tag": "💎 Secret Lagoon",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Bekal Beach & Fort",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Largest keyhole-shaped fort in Kerala rising directly out of the Arabian Sea waves, featured in legendary cinema.",
        "categories": ["beach"],
        "tag": "🏰 Ocean Fortress",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Dhanushkodi (Ghost Town Coast)",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 2 Days",
        "description": "Meeting point of Bay of Bengal and Indian Ocean (Arichal Munai) with submerged ruins of a legendary cyclone town.",
        "categories": ["beach"],
        "tag": "🌊 Land's End",
        "days": 2,
        "style": "Adventure"
    },
    {
        "name": "St. Mary's Island (Malpe)",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - May",
        "budget": "₹14,000 / 3 Days",
        "description": "Unique geological monument of volcanic hexagonal columnar basalt rock pillars rising from crystal blue waters.",
        "categories": ["beach"],
        "tag": "🗿 Basalt Pillars",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Karwar & Rabindranath Tagore Beach",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Apr",
        "budget": "₹15,000 / 3 Days",
        "description": "Kali river confluence with the Arabian Sea, Kurumgad island snorkeling, Warship museum, and Konkani cuisine.",
        "categories": ["beach"],
        "tag": "⚓ River Confluence",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Digha & Udaipur Beach",
        "state": "West Bengal & Odisha",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.4",
        "season": "Oct - Mar",
        "budget": "₹10,000 / 3 Days",
        "description": "Casuarina pine-lined tranquil shores on the Bengal-Odisha border with fresh prawn fries and scenic seaside walks.",
        "categories": ["beach"],
        "tag": "🌲 Casuarina Coast",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Yarada Beach",
        "state": "Visakhapatnam, Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "Secluded golden crescent beach surrounded by Dolphin's Nose hill on three sides and Bay of Bengal on the fourth.",
        "categories": ["beach"],
        "tag": "🐬 Dolphin Hills",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Cherai Beach",
        "state": "Kochi, Kerala",
        "img": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Sep - Mar",
        "budget": "₹15,000 / 3 Days",
        "description": "Unique 10 km beach strip where serene backwaters and sea run parallel with frequent Chinese fishing nets views.",
        "categories": ["beach"],
        "tag": "🛶 Sea & Backwater",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Devbagh Beach",
        "state": "Karwar, Karnataka",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - May",
        "budget": "₹16,000 / 3 Days",
        "description": "Private island jungle resort feeling with dolphins swimming alongside fishing boats and dense casuarina groves.",
        "categories": ["beach"],
        "tag": "🐬 Dolphin Island",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Rushikonda Beach",
        "state": "Visakhapatnam, Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "The 'Jewel of the East Coast' with Blue Flag eco-certification, windsurfing, speed boating, and pristine golden sands.",
        "categories": ["beach"],
        "tag": "🏄 Watersports Hub",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Muzhappilangad Drive-in Beach",
        "state": "Kannur, Kerala",
        "img": "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Apr",
        "budget": "₹14,000 / 3 Days",
        "description": "Asia's longest drive-in beach (4 km of firm golden sand) where cars and bikes can drive directly into the ocean sunset.",
        "categories": ["beach"],
        "tag": "🚗 Drive-in Beach",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Gopalpur-on-Sea",
        "state": "Odisha",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Oct - Mar",
        "budget": "₹11,000 / 3 Days",
        "description": "Ancient commercial seaport turned tranquil beach destination with an antique lighthouse and vintage heritage villas.",
        "categories": ["beach"],
        "tag": "🏮 Vintage Seaport",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Minicoy Island",
        "state": "Lakshadweep",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - May",
        "budget": "₹45,000 / 5 Days",
        "description": "Southernmost atoll of Lakshadweep with a historic 1885 British lighthouse, Maliku culture, and neon coral lagoons.",
        "categories": ["beach"],
        "tag": "🏝️ Atoll Lagoon",
        "days": 5,
        "style": "Luxury"
    },
    {
        "name": "Bangaram Atoll",
        "state": "Lakshadweep",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - May",
        "budget": "₹50,000 / 5 Days",
        "description": "Teardrop uninhabited coral island surrounded by shallow turquoise lagoons with turtles and bioluminescent plankton.",
        "categories": ["beach"],
        "tag": "✨ Bioluminescent Lagoon",
        "days": 5,
        "style": "Luxury"
    },
    {
        "name": "Butterfly Beach & Cabo de Rama",
        "state": "South Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - Apr",
        "budget": "₹18,000 / 3 Days",
        "description": "Hidden cove accessible only by boat or dense forest trek, famous for playful dolphins, sea butterflies, and cliff forts.",
        "categories": ["beach"],
        "tag": "🦋 Secret Cove",
        "days": 3,
        "style": "Adventure"
    },

    # =========================================================================
    # 🚗 ROAD TRIP (30 Unique Scenic Drives & Epic Corridors)
    # =========================================================================
    {
        "name": "Manali to Leh Highway",
        "state": "Himachal & Ladakh",
        "img": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Jun - Sep",
        "budget": "₹35,000 / 7 Days",
        "description": "The ultimate bucket-list high-altitude mountain highway crossing 5 mighty Himalayan passes over 490 km.",
        "categories": ["road-trip"],
        "tag": "🏍️ Bucket List",
        "days": 7,
        "style": "Adventure"
    },
    {
        "name": "Mumbai to Goa Coastal NH66",
        "state": "Maharashtra & Goa",
        "img": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Aug - Feb",
        "budget": "₹20,000 / 5 Days",
        "description": "Picturesque Konkan coastal highway lined with mango orchards, sea-bridge crossings, and hidden beach detours.",
        "categories": ["road-trip"],
        "tag": "🌊 Coastal Drive",
        "days": 5,
        "style": "Relaxed"
    },
    {
        "name": "Bangalore to Coorg & Wayanad",
        "state": "Karnataka & Kerala",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Mar",
        "budget": "₹16,000 / 4 Days",
        "description": "Lush Western Ghats curves through dense rainforests, aromatic coffee plantations, and mist-covered mountain passes.",
        "categories": ["road-trip"],
        "tag": "☕ Coffee Country",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Golden Triangle: Delhi - Agra - Jaipur",
        "state": "North India",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹22,000 / 5 Days",
        "description": "India's most iconic cultural route connecting the Taj Mahal, Amber Fort, Qutub Minar, and Rajasthani palaces.",
        "categories": ["road-trip"],
        "tag": "👑 Heritage Circuit",
        "days": 5,
        "style": "Family"
    },
    {
        "name": "Shillong to Cherrapunji & Dawki",
        "state": "Meghalaya",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Sep - May",
        "budget": "₹24,000 / 5 Days",
        "description": "Drive through swirling clouds, deep canyon gorges, towering waterfalls, and crystal mirror river waters at Dawki.",
        "categories": ["road-trip"],
        "tag": "☁️ Abode of Clouds",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "East Coast Road (Chennai to Pondy)",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "Scenic 150 km oceanfront highway hugging the Bay of Bengal passing Mahabalipuram shore temples and surf breaks.",
        "categories": ["road-trip"],
        "tag": "🛣️ Ocean Highway",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Ahmedabad to Rann of Kutch",
        "state": "Gujarat",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - Feb",
        "budget": "₹20,000 / 4 Days",
        "description": "Drive across desert highways leading to the endless white salt desert shimmering under full-moon skies and Rann Utsav.",
        "categories": ["road-trip"],
        "tag": "🌕 White Salt Desert",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Guwahati to Tawang High Pass Run",
        "state": "Assam & Arunachal Pradesh",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Apr - Oct",
        "budget": "₹34,000 / 6 Days",
        "description": "From Brahmaputra river valleys climbing 14,000 ft through cloud-wrapped Sela Pass, Dirang valleys, and monasteries.",
        "categories": ["road-trip"],
        "tag": "🏔️ Eastern Himalayas",
        "days": 6,
        "style": "Adventure"
    },
    {
        "name": "Shimla to Spiti Valley via Kinnaur",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "May - Oct",
        "budget": "₹28,000 / 7 Days",
        "description": "The Hindustan-Tibet road carved out of vertical cliff faces passing Sangla valley, Chitkul, Nako, and Tabo.",
        "categories": ["road-trip"],
        "tag": "🧗 Cliff-Carved Highway",
        "days": 7,
        "style": "Adventure"
    },
    {
        "name": "Bangalore to Ooty via Bandipur",
        "state": "Karnataka & Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - May",
        "budget": "₹15,000 / 3 Days",
        "description": "Drive through Bandipur and Mudumalai tiger reserves, navigating 36 famous hairpin bends into the Nilgiri hills.",
        "categories": ["road-trip"],
        "tag": "🐅 Tiger Safari Drive",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Jaipur to Jaisalmer Thar Drive",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹24,000 / 5 Days",
        "description": "Smooth golden desert highways through Jodhpur Blue City, Pokhran, ending at Sam sand dune desert camps.",
        "categories": ["road-trip"],
        "tag": "🏜️ Golden Sands",
        "days": 5,
        "style": "Luxury"
    },
    {
        "name": "Puri to Konark Marine Drive",
        "state": "Odisha",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹10,000 / 2 Days",
        "description": "35 km of oceanfront road with Bay of Bengal on one side and casuarina forests on the other, reaching the Sun Temple.",
        "categories": ["road-trip"],
        "tag": "☀️ Sun Temple Coast",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Visakhapatnam to Araku Valley",
        "state": "Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Sep - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "115 km winding Eastern Ghats ghats road with coffee plantations, tribal bazaars, and Borra limestone caves.",
        "categories": ["road-trip"],
        "tag": "☕ Ghats & Caves",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Kochi to Munnar via Gap Road",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Newly renovated cliff Gap Road slicing across clouds with cascading Cheeyappara falls and valley viewpoints.",
        "categories": ["road-trip"],
        "tag": "⛰️ Gap Road Clouds",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kolkata to Digha Expressway",
        "state": "West Bengal",
        "img": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Oct - Mar",
        "budget": "₹11,000 / 2 Days",
        "description": "Quick 180 km weekend escape crossing the Kolaghat bridge, rural Bengal farmlands, and coastal seafood shacks.",
        "categories": ["road-trip"],
        "tag": "🦀 Weekend Coast Drive",
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Dehradun to Mussoorie & Dhanaulti",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹14,000 / 3 Days",
        "description": "Sweeping mountain curves climbing 7,000 ft with views of the Doon Valley glittering below under night stars.",
        "categories": ["road-trip"],
        "tag": "✨ Doon Valley View",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Chandigarh to Kasol & Manali",
        "state": "Punjab & Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹16,000 / 4 Days",
        "description": "Kiratpur-Nerchowk expressway tunnels through Shivalik ranges leading directly into the Parvati & Kullu valleys.",
        "categories": ["road-trip"],
        "tag": "🚇 Tunnel Expressway",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Pune to Mahabaleshwar Western Ghats",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Jul - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "Khambatki and Pasarni ghat passes through strawberry farms, Mapro gardens, and table-land plateau cliffs at Panchgani.",
        "categories": ["road-trip"],
        "tag": "🍓 Strawberry Ghats",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Srinagar to Leh via Zoji La",
        "state": "Kashmir & Ladakh",
        "img": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "May - Oct",
        "budget": "₹32,000 / 6 Days",
        "description": "Sonamarg meadows crossing the thrilling Zoji La pass into Dras (second coldest inhabited place), Kargil, and Lamayuru.",
        "categories": ["road-trip"],
        "tag": "❄️ Zoji La Pass",
        "days": 6,
        "style": "Adventure"
    },
    {
        "name": "Siliguri to Gangtok (Teesta Run)",
        "state": "West Bengal & Sikkim",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun, Oct - Dec",
        "budget": "₹16,000 / 4 Days",
        "description": "Drive alongside the emerald green Teesta River with white water rapids, Coronation Bridge, and monastery views.",
        "categories": ["road-trip"],
        "tag": "🌊 Teesta River Valley",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Mangalore to Goa (Karwar Coastal NH66)",
        "state": "Karnataka & Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹18,000 / 4 Days",
        "description": "Arabian sea hugs the highway at Maravanthe where the river flows on the right and ocean waves crash on the left.",
        "categories": ["road-trip"],
        "tag": "🌊 Maravanthe Highway",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Delhi to Nainital & Corbett",
        "state": "Delhi & Uttarakhand",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Jun",
        "budget": "₹15,000 / 4 Days",
        "description": "Fast plains highway into Sal forests of Jim Corbett National Park and uphill curves around Naini Lake.",
        "categories": ["road-trip"],
        "tag": "🐅 Jungle to Lake",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Udaipur to Mount Abu Aravalli Run",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "Aravalli mountain highway passing marble factories, Ranakpur Jain temple, and Nakki Lake sunset points.",
        "categories": ["road-trip"],
        "tag": "🏰 Aravalli Pass",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Hyderabad to Hampi Heritage Route",
        "state": "Telangana & Karnataka",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 4 Days",
        "description": "370 km drive into boulder-strewn UNESCO Vijayanagara empire ruins, Tungabhadra river banks, and stone chariots.",
        "categories": ["road-trip"],
        "tag": "🏛️ Boulder Kingdom",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Mysore to Wayanad Forest Trail",
        "state": "Karnataka & Kerala",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "Drive through Muthanga Wildlife Sanctuary with deer and elephant crossings, leading into spice plantation homestays.",
        "categories": ["road-trip"],
        "tag": "🐘 Forest Safari Route",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Coimbatore to Valparai 40-Hairpin Run",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 3 Days",
        "description": "One of India's most thrilling ghat drives with 40 numbered hairpin turns rising above Aliyar Dam and evergreen forests.",
        "categories": ["road-trip"],
        "tag": "🔄 40 Hairpins",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Tezpur to Ziro Valley",
        "state": "Assam & Arunachal Pradesh",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Apr",
        "budget": "₹22,000 / 4 Days",
        "description": "Cross the Brahmaputra into virgin rainforests and bamboo groves of Lower Subansiri district.",
        "categories": ["road-trip"],
        "tag": "🎋 Rainforest Trail",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Leh to Nubra Valley via Khardung La",
        "state": "Ladakh",
        "img": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "May - Oct",
        "budget": "₹28,000 / 4 Days",
        "description": "Conquer 17,982 ft at Khardung La pass and descend into the Shyok river valley and Hunder desert oasis.",
        "categories": ["road-trip"],
        "tag": "🏔️ Highest Motorable Pass",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Port Blair to Diglipur (Andaman Trunk Road)",
        "state": "Andaman & Nicobar",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Apr",
        "budget": "₹32,000 / 5 Days",
        "description": "300 km jungle highway through Jarawa tribal reserve, Baratang mangrove boat caves, and Ross & Smith twin islands.",
        "categories": ["road-trip"],
        "tag": "🌴 Island Jungle Highway",
        "days": 5,
        "style": "Adventure"
    },
    {
        "name": "Bhopal to Pachmarhi Satpura Circuit",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "Drive through teak forests of Satpura Tiger Reserve climbing up to MP's only hill station with canyon waterfalls.",
        "categories": ["road-trip"],
        "tag": "🌲 Satpura Tiger Hills",
        "days": 3,
        "style": "Family"
    },

    # =========================================================================
    # 🌊 WATERFALL (30 Unique Cascades & Canyon Gorges)
    # =========================================================================
    {
        "name": "Athirappilly Falls",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Jun - Jan",
        "budget": "₹16,000 / 3 Days",
        "description": "The 'Niagara of India' — 80-foot wide thundering cascade amidst dense tropical Sholayar rainforest and hornbill birds.",
        "categories": ["waterfall"],
        "tag": "🌊 Niagara of India",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Nohkalikai Falls & Cherrapunji",
        "state": "Meghalaya",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "May - Dec",
        "budget": "₹22,000 / 4 Days",
        "description": "India's tallest plunge waterfall (1,115 ft) cascading from lush green tabletop cliffs into an emerald turquoise lagoon.",
        "categories": ["waterfall"],
        "tag": "💎 Tallest Plunge",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Jog Falls (Gerosoppa)",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Aug - Dec",
        "budget": "₹14,000 / 3 Days",
        "description": "Spectacular 4-tiered cascade (Raja, Roarer, Rocket, Rani) dropping 830 ft over Sharavathi river gorge cliffs.",
        "categories": ["waterfall"],
        "tag": "⚡ Mighty Cascade",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Dudhsagar Falls",
        "state": "Goa & Karnataka Border",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Jul - Jan",
        "budget": "₹15,000 / 3 Days",
        "description": "The 'Sea of Milk' — iconic 4-tiered 310-meter white cascade where railway viaduct bridges pass right through the mist.",
        "categories": ["waterfall"],
        "tag": "🥛 Sea of Milk",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Dhuandhar Falls & Marble Rocks",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "Smoky mist plunge on the sacred Narmada River carved into towering 100-foot white marble canyon gorges.",
        "categories": ["waterfall"],
        "tag": "🏛️ Marble Canyon",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Hogenakkal Falls",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Aug - Feb",
        "budget": "₹11,000 / 2 Days",
        "description": "Known as the Smoky Rocks on Kaveri river, famous for spinning circular coracle boat rides into the canyon spray.",
        "categories": ["waterfall"],
        "tag": "🚣 Coracle Boating",
        "days": 2,
        "style": "Adventure"
    },
    {
        "name": "Chitrakote Falls",
        "state": "Bastar, Chhattisgarh",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Jul - Jan",
        "budget": "₹14,000 / 3 Days",
        "description": "Widest waterfall in India (nearly 300 meters across in monsoon) on the Indravati river surrounded by Sal forests.",
        "categories": ["waterfall"],
        "tag": "🌊 Horseshoe Falls",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Elephant Falls",
        "state": "Shillong, Meghalaya",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹12,000 / 3 Days",
        "description": "Three-tiered cascade named by British officers set amidst fern-covered rocks just outside Shillong city.",
        "categories": ["waterfall"],
        "tag": "🌿 3-Tiered Falls",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Meenmutty Falls",
        "state": "Wayanad, Kerala",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "Magnificent 300-meter 3-tiered waterfall reached via a thrilling jungle trek through tea estates in Wayanad.",
        "categories": ["waterfall"],
        "tag": "🥾 Jungle Trek Falls",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Shivanasamudra Falls (Gaganachukki & Bharachukki)",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Jul - Nov",
        "budget": "₹10,000 / 2 Days",
        "description": "Twin segmented waterfalls where the Kaveri river splits around an island dropping 320 feet in massive volumes.",
        "categories": ["waterfall"],
        "tag": "⚡ Twin Kaveri Plunge",
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Kune Falls",
        "state": "Lonavala, Maharashtra",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jun - Oct",
        "budget": "₹11,000 / 2 Days",
        "description": "14th highest waterfall in India (200 meters) dropping across three tiers set against Sahyadri mountain backdrops.",
        "categories": ["waterfall"],
        "tag": "🌧️ Sahyadri Monsoons",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Thoseghar Falls",
        "state": "Satara, Maharashtra",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Jul - Nov",
        "budget": "₹12,000 / 2 Days",
        "description": "Spectacular 500-meter drop into a deep forested valley near Kaas Plateau flower meadows during monsoon.",
        "categories": ["waterfall"],
        "tag": "🌸 Kaas Valley Falls",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Abbey Falls (Abbi)",
        "state": "Coorg, Karnataka",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jul - Jan",
        "budget": "₹13,000 / 3 Days",
        "description": "Tucked away inside private coffee and spice plantations with a hanging bridge offering direct views of the falls.",
        "categories": ["waterfall"],
        "tag": "☕ Coffee Plantation Falls",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Hebbe Falls",
        "state": "Kemmangundi, Karnataka",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "550-foot two-stage cascade (Dodda Hebbe & Chikka Hebbe) accessible via 4x4 jungle jeep rides and herbal streams.",
        "categories": ["waterfall"],
        "tag": "🚙 4x4 Jeep Trek",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Soochipara Falls (Sentinel Rock)",
        "state": "Wayanad, Kerala",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹15,000 / 3 Days",
        "description": "Three-tiered waterfall surrounded by deciduous forests featuring a natural pool perfect for rock climbing and swimming.",
        "categories": ["waterfall"],
        "tag": "🧗 Rock Pool",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Nohsngithiang (Seven Sisters Falls)",
        "state": "Cherrapunji, Meghalaya",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Jun - Nov",
        "budget": "₹20,000 / 4 Days",
        "description": "Seven segmented streams tumbling over 1,033-foot limestone cliffs symbolizing the seven northeastern sister states.",
        "categories": ["waterfall"],
        "tag": "🌈 Seven Streams",
        "days": 4,
        "style": "Family"
    },
    {
        "name": "Bhagsu Falls",
        "state": "McLeodganj, Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹12,000 / 3 Days",
        "description": "30-foot mountain cascade near ancient Bhagsunath Temple, famous for Shiva cafes and cold glacial pool dips.",
        "categories": ["waterfall"],
        "tag": "🏔️ Himalayan Spring",
        "days": 3,
        "style": "Budget"
    },
    {
        "name": "Kempty Falls",
        "state": "Mussoorie, Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80",
        "rating": "4.4",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹13,000 / 3 Days",
        "description": "Colonial-era 40-foot waterfall cascade with ropeway cable car rides and shallow mountain swimming basins.",
        "categories": ["waterfall"],
        "tag": "🚠 Ropeway Falls",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Barehipani Falls",
        "state": "Simlipal, Odisha",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - May",
        "budget": "₹18,000 / 4 Days",
        "description": "Second highest waterfall in India (1,309 ft) two-tiered plunge in the heart of Simlipal Tiger Reserve.",
        "categories": ["waterfall"],
        "tag": "🐅 Tiger Reserve Cascade",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Courtallam Falls (Spa of South India)",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jul - Oct",
        "budget": "₹11,000 / 2 Days",
        "description": "Nine waterfalls in Western Ghats flowing through Ayurvedic herbal forests, believed to have natural medicinal healing waters.",
        "categories": ["waterfall"],
        "tag": "🌿 Herbal Spa Waters",
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Hundru Falls",
        "state": "Ranchi, Jharkhand",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Aug - Jan",
        "budget": "₹10,000 / 2 Days",
        "description": "320-foot Subarnarekha River cascade over eroded granite rocks forming a popular natural bathing pool.",
        "categories": ["waterfall"],
        "tag": "🗿 Granite Falls",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Sweet Falls",
        "state": "Shillong, Meghalaya",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Year-Round",
        "budget": "₹13,000 / 3 Days",
        "description": "96-meter sheer vertical water ribbon plummeting into a deep secluded gorge near Happy Valley, Shillong.",
        "categories": ["waterfall"],
        "tag": "🎀 Ribbon Plunge",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Talakona Falls",
        "state": "Tirupati, Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Sep - Jan",
        "budget": "₹11,000 / 2 Days",
        "description": "Highest waterfall in Andhra Pradesh (270 ft) nestled in Sri Venkateswara National Park with canopy rope-walks.",
        "categories": ["waterfall"],
        "tag": "🌉 Canopy Walk",
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Lodh Falls (Burha Gagh)",
        "state": "Latehar, Jharkhand",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jul - Jan",
        "budget": "₹12,000 / 3 Days",
        "description": "Highest waterfall in Jharkhand (469 ft) thundering across multiple steps inside the deciduous Betla forest.",
        "categories": ["waterfall"],
        "tag": "🌲 Forest Tiered Falls",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Catherine Falls",
        "state": "Kotagiri, Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "description": "Double-cascading 250-foot waterfall in Nilgiris viewed from Dolphin's Nose amidst tea gardens and pine ridges.",
        "categories": ["waterfall"],
        "tag": "🍵 Nilgiri Double Falls",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Pykara Falls & Lake",
        "state": "Ooty, Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jul - Feb",
        "budget": "₹13,000 / 3 Days",
        "description": "Sacred Toda river cascading in two segments over rocks below the Pykara boathouse and dam.",
        "categories": ["waterfall"],
        "tag": "🚤 Lake & Falls",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Chelavara Falls",
        "state": "Cheyyandane, Coorg",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Aug - Dec",
        "budget": "₹13,000 / 3 Days",
        "description": "Natural waterfall formed by small tributary near Chomakund hill known for tortoise-shaped rock formations.",
        "categories": ["waterfall"],
        "tag": "🐢 Tortoise Rock",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Iruppu Falls (Lakshmana Tirtha)",
        "state": "Brahmagiri, Coorg",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Jul - Jan",
        "budget": "₹14,000 / 3 Days",
        "description": "Fresh mountain water cascade inside Brahmagiri forest trail with Rameshwara temple at the foothills.",
        "categories": ["waterfall"],
        "tag": "🛕 Sacred Mountain Falls",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Arvalem Waterfalls (Harvalem)",
        "state": "Sanquelim, North Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.5",
        "season": "Jul - Dec",
        "budget": "₹12,000 / 2 Days",
        "description": "50-meter scenic waterfall near ancient 6th-century rock-cut Pandava Buddhist caves in peaceful North Goa hinterland.",
        "categories": ["waterfall"],
        "tag": "🗿 Ancient Cave Falls",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Mallalli Falls",
        "state": "Somwarpet, Coorg",
        "img": "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Jul - Dec",
        "budget": "₹14,000 / 3 Days",
        "description": "Kumaradhara river tumbling 200 ft over sheer steps at the foot of Pushpagiri hill in high volume during monsoons.",
        "categories": ["waterfall"],
        "tag": "⚡ Pushpagiri Plunge",
        "days": 3,
        "style": "Adventure"
    },

    # =========================================================================
    # ☕ CAFES & FOODIE CULTURE (30 Unique Bohemian, Heritage & Sunset Spots)
    # =========================================================================
    {
        "name": "Old Manali Riverside Cafes",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹15,000 / 4 Days",
        "description": "Bohemian riverside cafes with acoustic live jams, wood-fired apple trout pizza, artisanal coffee, and mountain views.",
        "categories": ["cafe"],
        "tag": "🎸 Bohemian Riverside",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Anjuna & Assagao Villa Cafes",
        "state": "Goa",
        "img": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - Apr",
        "budget": "₹25,000 / 4 Days",
        "description": "Restored Portuguese villa garden cafes, specialty third-wave coffee roasters, sourdough bakeries, and organic smoothie bowls.",
        "categories": ["cafe"],
        "tag": "☕ Artisanal Roasters",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Rishikesh Ganges Rooftop Cafes",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - May",
        "budget": "₹12,000 / 3 Days",
        "description": "River-facing panoramic terraces above Laxman Jhula serving Israeli shakshuka, herbal Ayurvedic teas, and sunset kombuchas.",
        "categories": ["cafe"],
        "tag": "🧘 Riverfront Wellness",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Landour Bakehouse & Cafes",
        "state": "Mussoorie, Uttarakhand",
        "img": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹14,000 / 3 Days",
        "description": "Colonial 19th-century pine hill bakery known for freshly baked lemon drizzle cake, cinnamon buns, and mountain mist.",
        "categories": ["cafe"],
        "tag": "🥧 Pine Hill Bakery",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Fort Kochi Art Heritage Cafes",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹18,000 / 4 Days",
        "description": "Dutch and Portuguese heritage bungalows converted into contemporary art cafes, bookshops, and coastal espresso bars.",
        "categories": ["cafe"],
        "tag": "🎨 Art & Espresso",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Dharamkot & McLeodganj Cafes",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹13,000 / 4 Days",
        "description": "Tibetan bakeries, vegan organic garden cafes, famous Bhagsu cake, and peaceful views overlooking the Kangra valley.",
        "categories": ["cafe"],
        "tag": "🏔️ Tibetan Bakery",
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Jaipur Royal Rooftop Cafes",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Candlelit royal rooftops overlooking the illuminated Hawa Mahal, spiced chai tastings, and Rajasthani fusion dining.",
        "categories": ["cafe"],
        "tag": "🏰 Royal Rooftops",
        "days": 3,
        "style": "Luxury"
    },
    {
        "name": "Pondicherry French White Town Bistros",
        "state": "Puducherry",
        "img": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Pastel yellow French colonial courtyards serving buttery croissants, crepes, iced cafe au lait, and sourdough baguettes.",
        "categories": ["cafe"],
        "tag": "🥐 French Croissants",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Kasol Parvati River Cafes",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹12,000 / 4 Days",
        "description": "Riverside wooden shacks serving freshly baked pita falafel, hummus platters, cinnamon rolls, and masala chai.",
        "categories": ["cafe"],
        "tag": "🥙 Israeli & Alpine",
        "days": 4,
        "style": "Budget"
    },
    {
        "name": "Bir Billing Tibetan Sunset Cafes",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Jun",
        "budget": "₹14,000 / 3 Days",
        "description": "Watch paragliders land against mountain sunsets while sipping pour-over coffee, Tibetan butter tea, and matcha pancakes.",
        "categories": ["cafe"],
        "tag": "🪂 Sunset & Gliders",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Darjeeling Glenary's Bakery & Lounge",
        "state": "West Bengal",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹15,000 / 3 Days",
        "description": "Century-old colonial bakery and jazz lounge with panoramic Kanchenjunga mountain views and Darjeeling first-flush tea.",
        "categories": ["cafe"],
        "tag": "☕ Century-Old Bakery",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Bangalore Church Street Specialty Roasters",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹14,000 / 3 Days",
        "description": "India's coffee capital hub with micro-roasters, third-wave pour-overs, bookshop cafes, and lively alfresco pedestrian vibes.",
        "categories": ["cafe"],
        "tag": "☕ Third-Wave Roasters",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Bandra & Kala Ghoda Heritage Cafes",
        "state": "Mumbai, Maharashtra",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹22,000 / 3 Days",
        "description": "Historic Parsi Irani chai cafes, artisanal sourdough bistros, and trendy sea-facing coffee houses in Mumbai's cultural district.",
        "categories": ["cafe"],
        "tag": "☕ Irani Chai & Bistros",
        "days": 3,
        "style": "Luxury"
    },
    {
        "name": "Panjim Fontainhas Latin Quarter Cafes",
        "state": "Goa",
        "img": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Year-Round",
        "budget": "₹18,000 / 3 Days",
        "description": "Quaint espresso bars and Portuguese patisseries tucked inside colourful 18th-century yellow and indigo colonial alleys.",
        "categories": ["cafe"],
        "tag": "🏘️ Latin Quarter",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Udaipur Lake Pichola Sunset Cafes",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹20,000 / 3 Days",
        "description": "Candlelit lakeside ghat cafes directly overlooking the illuminated City Palace and Jag Mandir reflected in calm waters.",
        "categories": ["cafe"],
        "tag": "🕯️ Lake View Dining",
        "days": 3,
        "style": "Luxury"
    },
    {
        "name": "Gangtok MG Marg Himalayan Cafes",
        "state": "Sikkim",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun, Oct - Dec",
        "budget": "₹15,000 / 3 Days",
        "description": "Clean pedestrian boulevard lined with cozy wooden cafes serving steamed momos, Sikkimese temba, and organic coffee.",
        "categories": ["cafe"],
        "tag": "🥟 Pedestrian Mall Cafes",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Shimla The Ridge Heritage Cafes",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹14,000 / 3 Days",
        "description": "Colonial-era coffee houses and bakeries facing Christ Church and snow-capped peaks on the car-free Mall Road.",
        "categories": ["cafe"],
        "tag": "⛪ Heritage Ridge",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Ooty Colonial Tea Lounges",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Year-Round",
        "budget": "₹15,000 / 3 Days",
        "description": "British colonial club tea rooms serving hot scones with homemade strawberry jam, Nilgiri white teas, and handmade chocolates.",
        "categories": ["cafe"],
        "tag": "🫖 High Tea & Scones",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Shillong Indie Music & Rock Cafes",
        "state": "Meghalaya",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - May",
        "budget": "₹14,000 / 3 Days",
        "description": "The 'Rock Capital of India' with vibrant live acoustic music bistros, Khasi culinary fusions, and specialty coffee beans.",
        "categories": ["cafe"],
        "tag": "🎸 Rock & Acoustic",
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Pushkar Sunset & Falafel Rooftops",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹10,000 / 3 Days",
        "description": "Bohemian rooftop cafes overlooking the sacred desert lake with laffa rolls, freshly brewed mint tea, and chanting bells.",
        "categories": ["cafe"],
        "tag": "🌅 Desert Lake Sunset",
        "days": 3,
        "style": "Budget"
    },
    {
        "name": "Mysore Heritage Sandalwood Cafes",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹11,000 / 2 Days",
        "description": "Authentic South Indian filter coffee in brass dabaras, hot Mysore Pak tastings, and vintage royal palace view terraces.",
        "categories": ["cafe"],
        "tag": "☕ Brass Filter Coffee",
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Varanasi Ghat Rooftop River Cafes",
        "state": "Uttar Pradesh",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹11,000 / 3 Days",
        "description": "Terraces overlooking Assi Ghat and Dashashwamedh Aarti serving wood-fired pizzas, lemon ginger honey tea, and thick lassi.",
        "categories": ["cafe"],
        "tag": "🛕 Ganga Aarti Terraces",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Coorg Coffee Estate Forest Bistros",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Open-air plantation cafes nestled among pepper vines and coffee shrubs serving estate single-origin brews and pandi curry.",
        "categories": ["cafe"],
        "tag": "☕ Estate Single-Origin",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Leh Changspa Garden Cafes",
        "state": "Ladakh",
        "img": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "May - Sep",
        "budget": "₹16,000 / 4 Days",
        "description": "High-altitude apple tree garden cafes in Leh serving wood-fired pizza, apricot cheesecakes, and yak cheese platters.",
        "categories": ["cafe"],
        "tag": "🍎 Apricot & Yak Cheese",
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Vagator & Chapora Cliffside Sunset Cafes",
        "state": "North Goa",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Apr",
        "budget": "₹22,000 / 3 Days",
        "description": "Cliff-edge outdoor lounges with deep-house sunset DJ sessions, kombuchas, and stunning panoramic views of the red sea cliffs.",
        "categories": ["cafe"],
        "tag": "🌅 Cliff Sunset Lounge",
        "days": 3,
        "style": "Luxury"
    },
    {
        "name": "Nainital Naini Lakeview Bistros",
        "state": "Uttarakhand",
        "img": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Year-Round",
        "budget": "₹13,000 / 3 Days",
        "description": "Lake-facing heritage bakeries and cafes on Mall Road with paddle boats drifting by and warm hot chocolate fudge.",
        "categories": ["cafe"],
        "tag": "🍫 Hot Chocolate Fudge",
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Jodhpur Blue City Rooftop Cafes",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹13,000 / 3 Days",
        "description": "Indigo blue rooftop cafes directly under the towering cliffs of Mehrangarh Fort with saffron makhaniya lassi and pyaaz kachoris.",
        "categories": ["cafe"],
        "tag": "🏰 Mehrangarh View",
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Alibaug Bohemian Coastal Shacks",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Apr",
        "budget": "₹15,000 / 2 Days",
        "description": "Coastal garden cafes set beneath swaying coconut palms serving fresh coconut cold brews and coastal sourdough pizzas.",
        "categories": ["cafe"],
        "tag": "🥥 Coconut Cold Brew",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Delhi Hauz Khas Village Artisan Cafes",
        "state": "Delhi",
        "img": "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Year-Round",
        "budget": "₹14,000 / 2 Days",
        "description": "Historic 14th-century medieval lake monument view terraces with indie art galleries, matcha bars, and specialty bakeries.",
        "categories": ["cafe"],
        "tag": "🏛️ Medieval Lake Cafe",
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Varkala Cliff Top Tibetan & Wellness Cafes",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹16,000 / 3 Days",
        "description": "Cliff-top bohemian bamboo cafes with ocean breezes, fresh ginger lemon honey tea, Tibetan thukpa, and sunset acoustic guitar.",
        "categories": ["cafe"],
        "tag": "🌊 Cliff Top Bamboo",
        "days": 3,
        "style": "Relaxed"
    },
]

VALID_CATEGORIES = {
    "mountains": {
        "title": "Mountain Destinations & Hidden Escapes",
        "icon": "🏔️",
        "description": "Explore 30 hand-picked mountain peaks, alpine secret valleys, and high passes across the Himalayas & Western Ghats."
    },
    "beach": {
        "title": "Beach Escapes & Secret Coastal Havens",
        "icon": "🏖️",
        "description": "Unwind across 30 golden sand beaches, cliffside shores, private coral atolls, and serene backwater coasts."
    },
    "road-trip": {
        "title": "Epic Road Trips & Scenic Drives",
        "icon": "🚗",
        "description": "Hit the highway on 30 legendary road trips across high Himalayan passes, coastal highways, and desert trails."
    },
    "waterfall": {
        "title": "Majestic Waterfalls & Canyon Cascades",
        "icon": "🌊",
        "description": "Discover 30 thundering rainforest cascades, emerald plunge pools, and boat-accessible canyon gorges."
    },
    "cafe": {
        "title": "Charming Cafes & Foodie Culture",
        "icon": "☕",
        "description": "Savor 30 artisanal coffee roasters, bohemian riverside shacks, colonial pine bakeries, and royal rooftop lounges."
    }
}


# =============================================================================
# 🔥 TRENDING DESTINATIONS (30 Brand-New Unique Places Not in Any Category)
# =============================================================================
TRENDING_DESTINATIONS = [
    {
        "name": "Hampi",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1600100397608-f010f443b740?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - Mar",
        "budget": "₹14,000 / 3 Days",
        "budget_num": 14000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Jaisalmer",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹18,000 / 4 Days",
        "budget_num": 18000,
        "days": 4,
        "style": "Luxury"
    },
    {
        "name": "Amritsar",
        "state": "Punjab",
        "img": "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - Mar",
        "budget": "₹10,000 / 2 Days",
        "budget_num": 10000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Kutch & Bhuj",
        "state": "Gujarat",
        "img": "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Nov - Feb",
        "budget": "₹19,000 / 4 Days",
        "budget_num": 19000,
        "days": 4,
        "style": "Relaxed"
    },
    {
        "name": "Majuli Island",
        "state": "Assam",
        "img": "https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹13,000 / 3 Days",
        "budget_num": 13000,
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Khajuraho",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1606298855672-3efb63017be8?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 2 Days",
        "budget_num": 12000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Pachmarhi",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Jun",
        "budget": "₹13,000 / 3 Days",
        "budget_num": 13000,
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Kodaikanal",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - May",
        "budget": "₹15,000 / 3 Days",
        "budget_num": 15000,
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Ranthambore",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Apr",
        "budget": "₹21,000 / 3 Days",
        "budget_num": 21000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Dirang & Bomdila",
        "state": "Arunachal Pradesh",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Mar - Oct",
        "budget": "₹22,000 / 4 Days",
        "budget_num": 22000,
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Orchha",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹11,000 / 2 Days",
        "budget_num": 11000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Bikaner",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹13,000 / 3 Days",
        "budget_num": 13000,
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Mandu",
        "state": "Madhya Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Jul - Mar",
        "budget": "₹11,000 / 2 Days",
        "budget_num": 11000,
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Kumarakom",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Mar",
        "budget": "₹24,000 / 3 Days",
        "budget_num": 24000,
        "days": 3,
        "style": "Luxury"
    },
    {
        "name": "Silent Valley",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "budget_num": 14000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Gandikota",
        "state": "Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Sep - Feb",
        "budget": "₹12,000 / 2 Days",
        "budget_num": 12000,
        "days": 2,
        "style": "Adventure"
    },
    {
        "name": "Ajanta & Ellora",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Oct - Mar",
        "budget": "₹15,000 / 3 Days",
        "budget_num": 15000,
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Badami & Pattadakal",
        "state": "Karnataka",
        "img": "https://images.unsplash.com/photo-1600100397608-f010f443b740?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 2 Days",
        "budget_num": 12000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Loktak Lake",
        "state": "Manipur",
        "img": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Apr",
        "budget": "₹18,000 / 3 Days",
        "budget_num": 18000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Dzukou Valley",
        "state": "Nagaland",
        "img": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
        "rating": "4.9",
        "season": "Jun - Sep (Lilies), Oct - Mar",
        "budget": "₹16,000 / 4 Days",
        "budget_num": 16000,
        "days": 4,
        "style": "Adventure"
    },
    {
        "name": "Rameshwaram",
        "state": "Tamil Nadu",
        "img": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Apr",
        "budget": "₹13,000 / 3 Days",
        "budget_num": 13000,
        "days": 3,
        "style": "Family"
    },
    {
        "name": "Sundarbans",
        "state": "West Bengal",
        "img": "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹14,000 / 3 Days",
        "budget_num": 14000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Poovar Island",
        "state": "Kerala",
        "img": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Sep - Mar",
        "budget": "₹17,000 / 3 Days",
        "budget_num": 17000,
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Bodh Gaya",
        "state": "Bihar",
        "img": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - Mar",
        "budget": "₹10,000 / 2 Days",
        "budget_num": 10000,
        "days": 2,
        "style": "Relaxed"
    },
    {
        "name": "Lepakshi",
        "state": "Andhra Pradesh",
        "img": "https://images.unsplash.com/photo-1600100397608-f010f443b740?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹8,000 / 2 Days",
        "budget_num": 8000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Haflong",
        "state": "Assam",
        "img": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Apr",
        "budget": "₹14,000 / 3 Days",
        "budget_num": 14000,
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Tadoba Andhari",
        "state": "Maharashtra",
        "img": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800&auto=format&fit=crop&q=80",
        "rating": "4.8",
        "season": "Oct - May",
        "budget": "₹20,000 / 3 Days",
        "budget_num": 20000,
        "days": 3,
        "style": "Adventure"
    },
    {
        "name": "Kumbhalgarh",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Oct - Mar",
        "budget": "₹14,000 / 2 Days",
        "budget_num": 14000,
        "days": 2,
        "style": "Family"
    },
    {
        "name": "Shekhawati",
        "state": "Rajasthan",
        "img": "https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?w=800&auto=format&fit=crop&q=80",
        "rating": "4.6",
        "season": "Oct - Mar",
        "budget": "₹12,000 / 3 Days",
        "budget_num": 12000,
        "days": 3,
        "style": "Relaxed"
    },
    {
        "name": "Chamba Valley",
        "state": "Himachal Pradesh",
        "img": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&auto=format&fit=crop&q=80",
        "rating": "4.7",
        "season": "Mar - Jun, Sep - Nov",
        "budget": "₹15,000 / 4 Days",
        "budget_num": 15000,
        "days": 4,
        "style": "Relaxed"
    },
]

